name: Basic CI

on:
  push:
    branches:
      - '**'

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Reset NX Cache
        run: pnpm nx reset

      - name: Format Check
        run: pnpm nx format:check apps/ libs/ src/

      - name: Lint Code
        run: pnpm nx run-many -t lint

      - name: Run Unit Tests
        run: pnpm nx run-many -t test
