name: CI (Main)

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: yarn install

      - name: Lint Code
        run: yarn fix-deps

      - name: Format Code
        run: yarn format

      - name: Build Project
        run: yarn build
