name: Deploy to Firebase Preview on merge to next branch

on:
    pull_request:
        branches:
            - next

permissions:
    checks: write
    contents: read
    pull-requests: write

jobs:
    build_and_preview:
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: 'yarn'
            - run: yarn install --frozen-lockfile && yarn build
            - name: Format Check
              run: yarn format
            - name: Lint Check
              run: yarn lint
            - name: Build
              run: yarn build
            - name: Storybook Build
              run: yarn build-storybook
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LAMENTIS_584565 }}
                  projectId: lamentis-584565
